name: 'Count Lines of Codes of AMF-Placer'
description: 'Generate the badges for the code line of your repositoryヾ(^▽^ヾ)'
inputs:
  path:  # id of input
    description: 'The file path of the generated badge file.'
    required: false
    default: 'cloc.svg'
outputs:
  path: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  branch: 'cloc_code'
branding:
  icon: 'code'
  color: 'orange'
