name: 'Count Lines of Codes of AMF-Placer'
description: 'Generate the badges for the code line of your repositoryヾ(^▽^ヾ)'
inputs:
  path:  # id of input
    description: 'The file path of the generated badge file.'
    required: false
    default: 'cloc.svg'
  github_token:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: true
    
outputs:
  path: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
branding:
  icon: 'code'
  color: 'orange'
